@startuml
start
:客户填写《测试申请表》
第1,2页和第3页的委托
单位信息；客户填写
《软件功能列表》;
:测试部人员审核委托;
:测试部人员填写《测试申
请表》第3页的密级,查杀
病毒,材料检查,确认意见;
:市场部人员审核委托;
:市场部人员填写受理意见;
#SkyBlue:if (是否受理) is (受理) then
#GreenYellow:市场部填写《报
价单》并生成报
价给客户;
else (不受理/进一步联系)
#Pink:委托结束;
kill
endif
' !pragma useVerticalIf on
#SkyBlue:if (客户是否接受) then (是)
else (否)
:市场部修改报价;
#SkyBlue:if (客户是否接受) then (否)
#Pink:委托结束;
kill
else (是)
endif
endif
:进入项目立项和合同评审流程;
:市场部人员填写测试项目
编号;受理人,委托人签字;
:市场部人员填写《测试合同》
第1,2页和第3页的合同价款;
repeat:市场部人员提供履行的期限给客户;
#SkyBlue:if (客户是否接受) then (是)
break
else (否)
endif
#LightGreen:if (客户是否申请再议) then (是)
else (否)
#Pink:委托结束;
endif
kill
repeat while ()
:市场部人员填写《测
试合同》履行的期限,
签章受托人的部分;
:客户填写《测试合同》
签章委托人部分;
:市场部填写《委托测试保密协议》;
:客户填写《委托测试保密协议》;
:前期指导工作结束;
stop
@enduml