@startuml 合同部分
start
:市场部人员填写测试项目编号,
受理人,委托人签字;
:市场部人员填写《测试合同》
第1,2页和第3页的合同价款;
repeat:市场部人员提供履行的期限给客户;
if (客户是否接受) then (是)
    break;

else (否)
    if (客户是否申请再议) then (否)
        :委托结束;
        kill;
    else (是)
        
    endif
endif
backward:客户申请再议;
repeat while;

:市场部人员填写《测试合同》
履行的期限,签章受托人的部分;
:客户填写《测试合同》
签章委托人部分;
:市场部填写《委托测试保密协议》;
:客户填写《委托测试保密协议》;
:前期指导工作结束;
stop
@enduml